version: "2"
linters:
  enable:
    - gocritic
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - gen
      - vendor
      - third_party$
      - builtin$
      - examples$
formatters:
  settings:
    goimports:
      local-prefixes:
        - github.com/Alevsk/respondent
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
