linters:
  enable:
    - govet
    - errcheck
    - staticcheck
    - unused
    - ineffassign
    - gocritic

linters-settings:
  goimports:
    local-prefixes: github.com/Alevsk/respondent

run:
  timeout: 5m

issues:
  exclude-dirs:
    - gen
    - vendor
